# Generated by Django 4.0.1 on 2022-04-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family',
            new_name='Friend',
        ),
    ]
