# Generated by Django 4.0.1 on 2022-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
            ],
        ),
    ]
