# Generated by Django 4.0.1 on 2022-04-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
